### ISSUE TITLE
关于播放器的一些建议

### ISSUE THREAD

**Issue by kaaass** [newraina/mePlayer#2]
很棒的播放器！不过建议加入一些好用的功能。

- 事件绑定，如APlayer一样

-  可以配置是否自动播放

**Comment by newraina** [comment]
谢谢~ 会考虑加入的~

**Comment by SportPlusX** [comment]
自动播放出来没，很喜欢这个播放器！支持！

**Comment by newraina** [comment]
@bpplpp 已经可以自动播放～
